apiVersion: v2
name: articles-chart
description: A Helm chart for the articles application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: kube-prometheus-stack
    version: 45.x.x
    repository: https://prometheus-community.github.io/helm-charts